### ISSUE TITLE
Socrata Datasets showing up as 8 character code instead of dataset name.

### ISSUE THREAD

**Issue by TwoWaves** [socrata/Socrata#11]
After connecting to NY Open Data with the plugin, retrieved datasets are listed in the QGIS table of contents as the 8 character code instead of showing the dataset name.  Example... 

y4ic-kfv6OGRGeoJSON      instead of      "Composting - Solid Waste Management Facilities Map"

In addition, while the NY Open Data website has 5,700 datasets with ~600 map/geo enabled,  the plugin returns ~100 datasets.  I have direct contact with the curator of NY Open Data and could ask then to change/update something with the datasets to make more of them discoverable by the plugin. What does the plugin search for when returning datasets from Socrata?

Using QGIS 3.6 and Socrata Plugin 2.1
Thanks!

**Comment by PeterAustinMoore** [comment]
Re: the number of results: that is a good catch. The plugin uses the [discovery api](https://socratadiscovery.docs.apiary.io/#) which has a default limit of 100 records per api call. So the plugin will have to updated to include a higher limit and/or pagination. Adding a bug tag to this issue.

Re: the ID vs Name, I went back and forth on this one. The dataset is called on its ID, so I thought it would be easier for searching on the root domain to get to the source dataset (plus you can change the name of the layer if you want). And since you can manually add the ID, it saved a call to get the dataset name prior to getting the data. But I get that in the Layer list, the ID is not particularly useful information. Perhaps a combination of the two (ID + Name) would suffice for both purposes?

**Comment by PeterAustinMoore** [comment]
@TwoWaves The [new version](https://plugins.qgis.org/plugins/Socrata/version/2.2/) is up for approval. 

It looks like for NY State in particular, they are aggregating from other domain sources, however the plugin will only search for maps that are native to data.ny.gov domain. From https://data.ny.gov/browse?federation_filter=297&limitTo=maps that looks to be currently 167 maps, which I verified is the count the plugin was pulling in.

The layers should now be {name} - {id} format.

**Comment by PeterAustinMoore** [comment]
New version has been approved
